import os


def make_credfile():
    """Utility function to make a file to store your hiev key that won't get 
    pushed to github. Simply call make_credfile() from the terminal and paste
    your key when it calls for it :)

    """
    key = input("please paste hiev key and hit enter: ")
    os.system("echo hiev_api_key='" + key + "' > credentials.py")
    # ensures credentials.py is not pushed to github
    os.system("echo credentials.py > .gitignore")
    print("Now you are ready to use\n\
          import credentials as c\n\
          key_file=c.hiev_api_key")


def is_toa5(record):
    """ Utility function to check if a supplied record (as generated by hievpy.search) is in TOA5 format

    Input
    -----
    Required
    - record: record object returned by the search function

    Returns
    -------
    True or False

    """

    if record['format'] == 'TOA5' and record['file_processing_status'] == 'RAW':
        return True

    return False
